INSERT INTO `emarket_test`.`category_info`
(`category_id`,`category_name`,`category_parent_id`,`category_creation_date`,`category_status`)
VALUES
-- Level 1 Categories --
(1,'Books',NULL,CURRENT_TIMESTAMP,TRUE),
(2,'Electronics',NULL,CURRENT_TIMESTAMP,TRUE),
(3,'Computers',NULL,CURRENT_TIMESTAMP,TRUE),
(4,'Clothing',NULL,CURRENT_TIMESTAMP,TRUE),
(5,'Sports',NULL,CURRENT_TIMESTAMP,TRUE),
-- Level 2 Categories --
(6,'Children',1,CURRENT_TIMESTAMP,TRUE),
(7,'Fiction',1,CURRENT_TIMESTAMP,TRUE),
(8,'Technology',1,CURRENT_TIMESTAMP,TRUE),
(9,'Business',1,CURRENT_TIMESTAMP,TRUE),
(10,'TV',2,CURRENT_TIMESTAMP,TRUE),
(11,'Audio',2,CURRENT_TIMESTAMP,TRUE),
(12,'Phones',2,CURRENT_TIMESTAMP,TRUE),
(13,'Cameras',2,CURRENT_TIMESTAMP,TRUE),
(14,'Video',2,CURRENT_TIMESTAMP,TRUE),
(15,'Laptops',3,CURRENT_TIMESTAMP,TRUE),
(16,'Desktops',3,CURRENT_TIMESTAMP,TRUE),
(17,'Tablets',3,CURRENT_TIMESTAMP,TRUE),
(18,'Printers',3,CURRENT_TIMESTAMP,TRUE),
(19,'Children',4,CURRENT_TIMESTAMP,TRUE),
(20,'Men',4,CURRENT_TIMESTAMP,TRUE),
(21,'Women',4,CURRENT_TIMESTAMP,TRUE),
(22,'Shoes',4,CURRENT_TIMESTAMP,TRUE),
(23,'Bicycles',5,CURRENT_TIMESTAMP,TRUE),
(24,'Fishing',5,CURRENT_TIMESTAMP,TRUE),
(25,'Baseball',5,CURRENT_TIMESTAMP,TRUE),
(26,'Gold',5,CURRENT_TIMESTAMP,TRUE),
(27,'Basketball',5,CURRENT_TIMESTAMP,TRUE),
-- Level 3 Categories --
(28,'Shirts',20,CURRENT_TIMESTAMP,TRUE),
(29,'Pants',20,CURRENT_TIMESTAMP,TRUE),
(30,'Socks',20,CURRENT_TIMESTAMP,TRUE),
(31,'Shirts',21,CURRENT_TIMESTAMP,TRUE),
(32,'Pants',21,CURRENT_TIMESTAMP,TRUE),
(33,'Dresses',21,CURRENT_TIMESTAMP,TRUE),
(34,'Children',22,CURRENT_TIMESTAMP,TRUE),
(35,'Women',22,CURRENT_TIMESTAMP,TRUE),
(36,'Men',22,CURRENT_TIMESTAMP,TRUE),
(37,'Frames',23,CURRENT_TIMESTAMP,TRUE),
(38,'Wheels',23,CURRENT_TIMESTAMP,TRUE),
(39,'Helmet',23,CURRENT_TIMESTAMP,TRUE),
(40,'Parts',23,CURRENT_TIMESTAMP,TRUE);
-- Special Purpose --
(41,'Other',NULL,CURRENT_TIMESTAMP,TRUE);
