INSERT INTO `emarket_test`.`notification_history`
(`notification_user_id`, `notification_message`, `notification_date`, `notification_is_read`)
VALUES
( 1, 'Lorem', CURRENT_TIMESTAMP, FALSE),
( 1, 'Lorem ipsum dolor', CURRENT_TIMESTAMP, TRUE),
( 1, 'Lorem ipsum dolor', CURRENT_TIMESTAMP, FALSE),
( 1, 'Lorem ipsum', CURRENT_TIMESTAMP, TRUE),
( 2, 'Lorem ipsum', CURRENT_TIMESTAMP, FALSE),
( 2, 'Lorem ipsum dolor sit amet,', CURRENT_TIMESTAMP, TRUE),
( 2, 'Lorem ipsum dolor sit amet,', CURRENT_TIMESTAMP, FALSE),
( 2, 'Lorem ipsum', CURRENT_TIMESTAMP, TRUE),
( 3, 'Lorem ipsum dolor', CURRENT_TIMESTAMP, FALSE),
( 3, 'Lorem ipsum', CURRENT_TIMESTAMP, TRUE),
( 3, 'Lorem ipsum dolor sit amet,', CURRENT_TIMESTAMP, FALSE),
( 3, 'Lorem ipsum', CURRENT_TIMESTAMP, TRUE),
( 4, 'Lorem ipsum', CURRENT_TIMESTAMP, FALSE),
( 4, 'Lorem ipsum dolor', CURRENT_TIMESTAMP, TRUE),
( 4, 'Lorem ipsum dolor sit amet, consectetuer', CURRENT_TIMESTAMP, FALSE),
( 4, 'Lorem ipsum', CURRENT_TIMESTAMP, TRUE),
( 5, 'Lorem ipsum dolor sit', CURRENT_TIMESTAMP, FALSE),
( 5, 'Lorem ipsum dolor', CURRENT_TIMESTAMP, TRUE),
( 5, 'Lorem ipsum dolor sit amet,', CURRENT_TIMESTAMP, FALSE),
( 5, 'Lorem ipsum dolor sit amet, consectetuer', CURRENT_TIMESTAMP, TRUE),
( 6, 'Lorem ipsum dolor', CURRENT_TIMESTAMP, FALSE),
( 6, 'Lorem ipsum dolor sit amet,', CURRENT_TIMESTAMP, TRUE),
( 6, 'Lorem', CURRENT_TIMESTAMP, FALSE),
( 6, 'Lorem ipsum', CURRENT_TIMESTAMP, TRUE),
( 7, 'Lorem ipsum dolor sit', CURRENT_TIMESTAMP, FALSE),
( 7, 'Lorem ipsum', CURRENT_TIMESTAMP, TRUE),
( 7, 'Lorem ipsum dolor sit amet, consectetuer', CURRENT_TIMESTAMP, FALSE),
( 7, 'Lorem ipsum dolor sit amet, consectetuer', CURRENT_TIMESTAMP, TRUE),
( 8, 'Lorem ipsum dolor sit amet, consectetuer', CURRENT_TIMESTAMP, FALSE),
( 8, 'Lorem', CURRENT_TIMESTAMP, TRUE),
( 8, 'Lorem ipsum', CURRENT_TIMESTAMP, FALSE),
( 8, 'Lorem ipsum dolor sit amet, consectetuer', CURRENT_TIMESTAMP, TRUE),
( 9, 'Lorem ipsum dolor sit', CURRENT_TIMESTAMP, FALSE),
( 9, 'Lorem ipsum dolor sit', CURRENT_TIMESTAMP, TRUE),
( 9, 'Lorem ipsum', CURRENT_TIMESTAMP, FALSE),
( 9, 'Lorem ipsum dolor sit amet,', CURRENT_TIMESTAMP, TRUE),
( 10, 'Lorem ipsum dolor', CURRENT_TIMESTAMP, FALSE),
( 10, 'Lorem', CURRENT_TIMESTAMP, TRUE),
( 10, 'Lorem', CURRENT_TIMESTAMP, FALSE),
( 10, 'Lorem ipsum dolor sit amet, consectetuer', CURRENT_TIMESTAMP, TRUE),
( 11, 'Lorem ipsum', CURRENT_TIMESTAMP, FALSE),
( 11, 'Lorem ipsum dolor sit amet, consectetuer', CURRENT_TIMESTAMP, TRUE),
( 11, 'Lorem', CURRENT_TIMESTAMP, FALSE),
( 11, 'Lorem ipsum dolor sit', CURRENT_TIMESTAMP, TRUE),
( 12, 'Lorem ipsum dolor', CURRENT_TIMESTAMP, FALSE),
( 12, 'Lorem', CURRENT_TIMESTAMP, TRUE),
( 12, 'Lorem ipsum dolor sit amet,', CURRENT_TIMESTAMP, FALSE),
( 12, 'Lorem', CURRENT_TIMESTAMP, TRUE),
( 13, 'Lorem ipsum dolor', CURRENT_TIMESTAMP, FALSE),
( 13, 'Lorem ipsum dolor', CURRENT_TIMESTAMP, TRUE),
( 13, 'Lorem ipsum dolor sit amet, consectetuer', CURRENT_TIMESTAMP, FALSE),
( 13, 'Lorem ipsum dolor sit amet, consectetuer', CURRENT_TIMESTAMP, TRUE),
( 14, 'Lorem ipsum', CURRENT_TIMESTAMP, FALSE),
( 14, 'Lorem', CURRENT_TIMESTAMP, TRUE),
( 14, 'Lorem ipsum', CURRENT_TIMESTAMP, FALSE),
( 14, 'Lorem ipsum dolor sit amet, consectetuer', CURRENT_TIMESTAMP, TRUE),
( 15, 'Lorem ipsum dolor', CURRENT_TIMESTAMP, FALSE),
( 15, 'Lorem', CURRENT_TIMESTAMP, TRUE),
( 15, 'Lorem ipsum dolor sit amet, consectetuer', CURRENT_TIMESTAMP, FALSE),
( 15, 'Lorem ipsum', CURRENT_TIMESTAMP, TRUE);
