INSERT INTO `emarket_test`.`product_drafts`

(`product_draft_user_id`, `product_draft_spec_id`, `product_draft_creation_date`, `product_draft_update_date`, `product_draft_closed_date`)

VALUES

( 1, 1, CURRENT_TIMESTAMP, NULL, NULL),
( 1, 3, CURRENT_TIMESTAMP, NULL, NULL),
( 1, 5, CURRENT_TIMESTAMP, NULL, NULL),

( 2, 7, CURRENT_TIMESTAMP, NULL, NULL),
( 2, 9, CURRENT_TIMESTAMP, NULL, NULL),

( 3, 11, CURRENT_TIMESTAMP, NULL, NULL),
( 3, 13, CURRENT_TIMESTAMP, NULL, NULL),
( 3, 15, CURRENT_TIMESTAMP, NULL, NULL),

( 4, 17, CURRENT_TIMESTAMP, NULL, NULL),
( 4, 19, CURRENT_TIMESTAMP, NULL, NULL),

( 5, 21, CURRENT_TIMESTAMP, NULL, NULL),
( 5, 23, CURRENT_TIMESTAMP, NULL, NULL),
( 5, 25, CURRENT_TIMESTAMP, NULL, NULL),
( 5, 27, CURRENT_TIMESTAMP, NULL, NULL),
( 5, 29, CURRENT_TIMESTAMP, NULL, NULL),

( 6, 31, CURRENT_TIMESTAMP, NULL, NULL),
( 6, 33, CURRENT_TIMESTAMP, NULL, NULL),
( 6, 35, CURRENT_TIMESTAMP, NULL, NULL),
( 6, 37, CURRENT_TIMESTAMP, NULL, NULL),
( 6, 39, CURRENT_TIMESTAMP, NULL, NULL),

( 7, 41, CURRENT_TIMESTAMP, NULL, NULL),
( 7, 43, CURRENT_TIMESTAMP, NULL, NULL),
( 7, 45, CURRENT_TIMESTAMP, NULL, NULL),
( 7, 47, CURRENT_TIMESTAMP, NULL, NULL),
( 7, 49, CURRENT_TIMESTAMP, NULL, NULL),

( 8, 51, CURRENT_TIMESTAMP, NULL, NULL),
( 8, 53, CURRENT_TIMESTAMP, NULL, NULL),
( 8, 55, CURRENT_TIMESTAMP, NULL, NULL),
( 8, 57, CURRENT_TIMESTAMP, NULL, NULL),
( 8, 59, CURRENT_TIMESTAMP, NULL, NULL),

( 13, 61, CURRENT_TIMESTAMP, NULL, NULL),
( 13, 63, CURRENT_TIMESTAMP, NULL, NULL),
( 13, 65, CURRENT_TIMESTAMP, NULL, NULL),
( 13, 67, CURRENT_TIMESTAMP, NULL, NULL),
( 13, 69, CURRENT_TIMESTAMP, NULL, NULL),

( 14, 71, CURRENT_TIMESTAMP, NULL, NULL),
( 14, 73, CURRENT_TIMESTAMP, NULL, NULL),
( 14, 75, CURRENT_TIMESTAMP, NULL, NULL),
( 14, 77, CURRENT_TIMESTAMP, NULL, NULL),
( 14, 79, CURRENT_TIMESTAMP, NULL, NULL);
