INSERT INTO `emarket_test`.`question_answer_history`
(`answer_question_id`, `answer_user_id`, `answer_content`, `answer_status`)
VALUES
( 1, 1, 'Pincho', TRUE),
( 2, 1, 'Manuel', TRUE),
( 3, 1, 'Humacao', TRUE),
( 4, 1, 'San Juan', FALSE),
( 5, 1, 'Rosa', FALSE),
( 6, 2, 'Carolina', TRUE),
( 7, 2, 'Doctor', TRUE),
( 8, 2, 'Pollos Ahumados Inc.', TRUE),
( 9, 2, 'Green Lantern', FALSE),
( 1, 2, 'TresPote', FALSE),
( 2, 3, 'Juan', TRUE),
( 3, 3, 'Texas', TRUE),
( 4, 3, 'Florida', TRUE),
( 5, 3, 'Pulga', FALSE),
( 6, 3, 'Barceloneta', FALSE),
( 7, 4, 'Scientist', TRUE),
( 8, 4, 'Carnes Adobadas Org.', TRUE),
( 9, 4, 'SuperMan', TRUE),
( 1, 4, 'Canoa', FALSE),
( 2, 4, 'Arturo', FALSE),
( 3, 5, 'Europe', TRUE),
( 4, 5, 'Jersey City', TRUE),
( 5, 5, 'Espada', TRUE),
( 6, 5, 'Cayey', FALSE),
( 7, 5, 'Athlete', FALSE),
( 8, 6, 'Limpia Techos Inc.', TRUE),
( 9, 6, 'Mami', TRUE),
( 1, 6, 'Bimbo', TRUE),
( 2, 6, 'Sonia', FALSE),
( 3, 6, 'Norway', FALSE),
( 4, 7, 'Tucson', TRUE),
( 5, 7, 'Sotomayor', TRUE),
( 6, 7, 'Guayama', TRUE),
( 7, 7, 'FireFighter', FALSE),
( 8, 7, 'Pollos Hermanos Inc.', FALSE),
( 9, 8, 'Papi', TRUE),
( 1, 8, 'Caramelo', TRUE),
( 2, 8, 'Linda', TRUE),
( 3, 8, 'England', FALSE),
( 4, 8, 'Mountain View', FALSE),
( 5, 9, 'Feliciano', TRUE),
( 6, 9, 'Hormigueros', TRUE),
( 7, 9, 'Judge', TRUE),
( 8, 9, 'Limpia Zapatos Org.', FALSE),
( 9, 9, 'Hulk', FALSE),
( 1, 10, 'Pelua', TRUE),
( 2, 10, 'Victor', TRUE),
( 3, 10, 'Nigeria', TRUE),
( 4, 10, 'Canada', FALSE),
( 5, 10, 'Joan', FALSE),
( 6, 11, 'Canovanas', TRUE),
( 7, 11, 'PoliceMan', TRUE),
( 8, 11, 'Pinchos, Aguacates y Algo Mas Inc.', TRUE),
( 9, 11, 'Batman', FALSE),
( 1, 11, 'Pancho', FALSE),
( 2, 12, 'Kimberly', TRUE),
( 3, 12, 'Fajardo', TRUE),
( 4, 12, 'Russia', TRUE),
( 5, 12, 'Mestizos', FALSE),
( 6, 12, 'Dorado', FALSE),
( 7, 13, 'Janitor', TRUE),
( 8, 13, 'Cerdos Online Inc.', TRUE),
( 9, 13, 'IronMan', TRUE),
( 1, 13, 'Noticia', FALSE),
( 2, 13, 'Maria', FALSE),
( 3, 14, 'Mayaguez', TRUE),
( 4, 14, 'Japan', TRUE),
( 5, 14, 'Cerveceros', TRUE),
( 6, 14, 'Aguadilla', FALSE),
( 7, 14, 'CEO', FALSE),
( 8, 15, 'Cerveza Fria Org.', TRUE),
( 9, 15, 'Manuel Rodriguez', TRUE),
( 1, 15, 'Pepe', TRUE),
( 2, 15, 'Jose', FALSE),
( 3, 15, 'Ponce', FALSE);